Some changes in cpplint arguments and inside of cpplint itself.

diff --git a/codestyle/pre-commit b/codestyle/pre-commit
--- a/codestyle/pre-commit
+++ b/codestyle/pre-commit
@@ -7,21 +7,38 @@
 #
 # To enable this hook, rename this file to "pre-commit".
 
+PROJECT_PATH="."
 
-if ! python codestyle/cpplint.py --root=./ --linelength=120 --recursive *
+CODESTYLE_PATH="$PROJECT_PATH/codestyle"
+
+CPPLINT_LOG="$CODESTYLE_PATH/cpplint.stderr"
+
+if ! sh -c "python $CODESTYLE_PATH/cpplint.py \
+        --root=$PROJECT_PATH/ \
+        --linelength=120 \
+        --exclude=CMakeFiles \
+        --recursive \
+        --headers=h \
+        --extensions=cpp \
+        $PROJECT_PATH/*" 2> $CPPLINT_LOG
 then
-    echo "Codestyle check failed"
+    echo "Codestyle check failed. See report:"
+    cat $CPPLINT_LOG
+    rm -f $CPPLINT_LOG
     exit 1
 else
     echo "Codestyle check succeed"
+    exit 0
 fi
+
+rm -f $CPPLINT_LOG
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
-	against=HEAD
+    against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+    # Initial commit: diff against an empty tree object
+    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
@@ -34,13 +51,13 @@ exec 1>&2
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+    # Note that the use of brackets around a tr range is ok here, (it's
+    # even required, for portability to Solaris 10's /usr/bin/tr), since
+    # the square bracket bytes happen to fall in the designated range.
+    test $(git diff --cached --name-only --diff-filter=A -z $against |
+      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
-	cat <<\EOF
+    cat <<\EOF
 Error: Attempt to add a non-ASCII file name.
 
 This can cause problems if you want to work with people on other platforms.
@@ -51,7 +68,7 @@ If you know what you are doing you can disable this check using:
 
   git config hooks.allownonascii true
 EOF
-	exit 1
+    exit 1
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
